#!/usr/bin/env python3
"""Seed packages/hd_battle's enemy table from the RPG-side table.

One-shot conversion, kept so it can be re-run and diffed (B1-02). The
source table came out of the legacy Hadar binaries via tools/, so
retyping it by hand would introduce typos; this reads it instead.

  python3 tools/battle/convert_enemy_table.py

Reads : hadar2026_app/lib/domain/battle/enemy_data.dart
Writes: packages/hd_battle/lib/src/data/enemy_table.dart
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / 'hadar2026_app/lib/domain/battle/enemy_data.dart'
DST = ROOT / 'packages/hd_battle/lib/src/data/enemy_table.dart'

ROW = re.compile(
    r"HDEnemyData\(id:\s*(\d+),\s*name:\s*'([^']*)',\s*strength:\s*(-?\d+),"
    r"\s*mentality:\s*(-?\d+),\s*endurance:\s*(-?\d+),\s*resistance:\s*(-?\d+),"
    r"\s*agility:\s*(-?\d+),\s*accuracy:\s*\[(-?\d+),\s*(-?\d+)\],"
    r"\s*ac:\s*(-?\d+),\s*special:\s*(-?\d+),\s*castLevel:\s*(-?\d+),"
    r"\s*specialCastLevel:\s*(-?\d+),\s*level:\s*(-?\d+)\)")


def to_snake(name: str) -> str:
    s = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name)
    s = re.sub(r'[^A-Za-z0-9]+', '_', s)
    return s.strip('_').lower()


def main() -> int:
    rows = ROW.findall(SRC.read_text())
    if not rows:
        print(f'no rows matched in {SRC}', file=sys.stderr)
        return 1

    ids = [int(r[0]) for r in rows]
    if ids != list(range(len(ids))):
        print(f'ids are not 0..{len(ids) - 1}: {ids}', file=sys.stderr)
        return 1

    keys, seen = [], {}
    for r in rows:
        k = to_snake(r[1])
        seen[k] = seen.get(k, 0) + 1
        keys.append(k if seen[k] == 1 else f'{k}_{seen[k]}')

    out = [
        '// GENERATED by tools/battle/convert_enemy_table.py — do not edit by hand.',
        '//',
        "// Seeded once from the RPG side's table",
        '// (hadar2026_app/lib/domain/battle/enemy_data.dart, 75 rows, ids 0..74).',
        '// The battle owns this table from here on and is free to grow it; re-run',
        '// the script only to re-check the seeded numbers against the source.',
        '//',
        '// Identity is [EnemyData.key], a snake_case string, not an index.',
        '// [EnemyData.legacyId] preserves the original index so the CM2 adapter',
        "// can still answer `Battle::RegisterEnemy(26)` (B3-01).",
        '',
        '/// One row of the enemy table. Immutable reference data.',
        'class EnemyData {',
        '  const EnemyData({',
        '    required this.key,',
        '    required this.legacyId,',
        '    required this.name,',
        '    required this.strength,',
        '    required this.mentality,',
        '    required this.endurance,',
        '    required this.resistance,',
        '    required this.agility,',
        '    required this.accuracy,',
        '    required this.ac,',
        '    required this.special,',
        '    required this.castLevel,',
        '    required this.specialCastLevel,',
        '    required this.level,',
        '  });',
        '',
        '  /// Stable identity. Never derive this from a list position.',
        '  final String key;',
        '',
        "  /// Index this row had in the RPG side's table (0..74).",
        '  final int legacyId;',
        '',
        '  /// Display name, as the original shipped it.',
        '  final String name;',
        '',
        '  final int strength;',
        '  final int mentality;',
        '  final int endurance;',
        '  final int resistance;',
        '  final int agility;',
        '',
        '  /// `[physical, magical]`.',
        '  final List<int> accuracy;',
        '',
        '  final int ac;',
        '  final int special;',
        '  final int castLevel;',
        '  final int specialCastLevel;',
        '  final int level;',
        '}',
        '',
        '/// The whole table, in legacy id order.',
        'const List<EnemyData> enemyTable = [',
    ]
    for key, r in zip(keys, rows):
        (rid, name, st, me, en, re_, ag, a0, a1, ac, sp, cl, scl, lv) = r
        out.append(
            f"  EnemyData(key: '{key}', legacyId: {rid}, name: '{name}', "
            f"strength: {st}, mentality: {me}, endurance: {en}, "
            f"resistance: {re_}, agility: {ag}, accuracy: [{a0}, {a1}], "
            f"ac: {ac}, special: {sp}, castLevel: {cl}, "
            f"specialCastLevel: {scl}, level: {lv}),")
    out += [
        '];',
        '',
        '/// Lookup by [EnemyData.key]. Built once.',
        'final Map<String, EnemyData> enemyByKey = {',
        '  for (final e in enemyTable) e.key: e,',
        '};',
        '',
        '/// Lookup by the legacy index the CM2 scripts still use.',
        'final Map<int, EnemyData> enemyByLegacyId = {',
        '  for (final e in enemyTable) e.legacyId: e,',
        '};',
        '',
    ]
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text('\n'.join(out))
    print(f'{len(rows)} rows -> {DST.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
